title        : "晓航的网站"
author       : "李晓航"
lang         : "zh-Hans"

url          : "https://shon.li"
fullurl      : "shon.li"
permalink    : none

collections  :
  categories :
  output     : false

plugins      :
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag