# Custom file directories
source          : ./source
destination     : ./destination

# URLs
url             : "https://shon.li"
fullurl         : "shon.li"
permalink       : none

# Default front matter for all pages and posts
defaults        :
  -
    scope       :
      path      : ""
    values      :
      layout    : "default"
      lang      : "zh-Hans"
      copyright : true

# Config for compress-html layout
compress_html   :
  clippings     : all
  comments      : []
  endings       : all
  ignore        :
    envs        : []
  blanklines    : false
  profile       : false
  startings     : []

# Sass
sass:
    style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag